cacheFolder: ./.yarn/cache

defaultSemverRangePrefix: ""

enableMessageNames: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

packageExtensions:
  "@rsuite/icons@*":
    dependencies:
      "@babel/runtime": "*"
      "prop-types": "*"

yarnPath: .yarn/releases/yarn-berry.js
