name: Create Prod Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout relevant branches
      run: |
       git checkout prod
       git branch -f main ${{ github.sha }}
    - name: Initialize git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Create merge commit
      run: |
       git merge main
       git push origin prod
